[package]
name = "blackbar_remover"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O1"]
